version: "3.9"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: wakabi:latest
    volumes:
      - ./wakabi:/app/wakabi
  db:
    image: postgres:10-alpine
    volumes:
      - ./shared/pg_db:/var/lib/postgresql/data
    restart: always
    ports:
      - "45432:5432"
    environment:
      PG_HOST: ${PG_HOST}
      PG_PORT: ${PG_PORT}
      PG_DATABASE: ${PG_DATABASE}
      PG_USER: ${PG_USER}
      PG_PASSWORD: ${PG_PASSWORD}
